### ISSUE TITLE
feat(react-router-dom): crear routing structure

### ISSUE THREAD

**Issue by sotomaque** [sotomaque/react-cinema-app#29]
### Summary
- wrap app with router
- create routes
    - Home Page Route
    - Login route
    - Sign up route
    - 404

### Subtasks
- [x] create home page
- [x] create login page
- [x] create sign up page
- [x] create custom 404 page
